- id: frappe-coding-standards
  name: Frappe Coding Standards Check
  description: Check general coding standards for Frappe Framework projects
  entry: frappe-pre-commit-coding-standards
  language: python
  additional_dependencies: [frappe-pre-commit]
  files: \.py$
  pass_filenames: true

- id: frappe-sql-security
  name: Frappe SQL Security Check
  description: Check for SQL injection vulnerabilities and security issues
  entry: frappe-pre-commit-sql-security
  language: python
  additional_dependencies: [frappe-pre-commit]
  files: \.py$
  pass_filenames: true

- id: frappe-doctype-naming
  name: Frappe DocType Naming Check
  description: Check DocType and field naming conventions
  entry: frappe-pre-commit-doctype-naming
  language: python
  additional_dependencies: [frappe-pre-commit]
  files: \.(py|js|json)$
  pass_filenames: true