# Copy this to your project root as .pre-commit-config.yaml

repos:
  # Code formatting with Ruff (fast Python linter/formatter)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        name: "Ruff import sorter"
        args: ["--select=I", "--fix"]

      - id: ruff
        name: "Ruff linter"
        args: ["--extend-ignore=E501"]  # Ignore line length, handled by formatter

      - id: ruff-format
        name: "Ruff formatter"

  # JavaScript/CSS/JSON formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|css|scss|json|md|yml|yaml)$
        exclude: |
          (?x)^(
              .*\.min\.(js|css)$|
              node_modules/.*|
              .*/static/.*|
              .*/public/.*
          )$

  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: \.(md|rst)$
      - id: end-of-file-fixer
        exclude: \.(md|rst)$
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements

  # Frappe-specific coding standards
  - repo: https://github.com/dhwani-ris/frappe-pre-commit
    rev: v1.0.0  # Use latest tag
    hooks:
      - id: frappe-translation-check
      - id: frappe-sql-security
      - id: frappe-doctype-naming
      - id: frappe-coding-standards

# Alternative: Use all checks in one hook
# - repo: https://github.com/dhwani-ris/frappe-pre-commit
#   rev: v1.0.0
#   hooks:
#     - id: frappe-all-checks

# Configuration for specific tools
default_language_version:
  python: python3

# Global excludes
exclude: |
  (?x)^(
      .*/migrations/.*|
      .*/patches/.*|
      .*\.min\.(js|css)$|
      node_modules/.*|
      .git/.*|
      __pycache__/.*|
      .*\.pyc$|
      build/.*|
      dist/.*|
      .eggs/.*
  )$